Polkit (#18)
shadow/polkit/linux-pam: fully optional

diff --git a/extra/polkit/build b/extra/polkit/build
--- a/extra/polkit/build
+++ b/extra/polkit/build
@@ -1,5 +1,10 @@
 #!/bin/sh -e
 
+kiss l linux-pam || kiss l shadow || {
+    printf 'linux-pam or shadow is required\n'
+    exit 1
+}
+
 for patch in *.patch; do
     patch -p1 < $patch
 done
@@ -33,6 +38,7 @@ patch -p1 < remove-intltool.oops
 # or not to include libelogind support.
 
 pkg-config --exists libelogind || libelogind=no
+kiss l linux-pam || auth=shadow
 
 ./configure \
     --prefix=/usr \
@@ -48,11 +54,14 @@ pkg-config --exists libelogind || libelogind=no
     --enable-libsystemd-login=no \
     --enable-libelogind="${libelogind:-yes}" \
     --with-backend=keyfile \
-    --with-authfw=pam \
+    --with-authfw="${auth:-pam}" \
     --with-os-type=KISS
 
 make
 make DESTDIR="$1" install
 
 install -Dm755 polkit.run "$1/etc/sv/polkitd/run"
-install -Dm644 polkit.pam "$1/etc/pam.d/polkit-1"
+
+if kiss l linux-pam; then
+    install -Dm644 polkit.pam "$1/etc/pam.d/polkit-1"
+fi
